version: "3"
services:
  mysql-poke:
    container_name: mysql-poke
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pokewith
      MYSQL_ROOT_PASSWORD: root1234
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/mysql-init.d:/docker-entrypoint-initdb.d
    networks:
      - poke-network
  redis-poke:
    container_name: redis-poke
    image: redis:6.0.5
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    networks:
      - poke-network
  spring-poke:
    container_name: spring-poke
    image: openjdk:17-jdk
    ports:
      - "8888:8888"
    depends_on:
      - mysql-poke
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command:
      - |
        ./gradlew clean
        ./gradlew bootrun -x test
    restart: on-failure
    networks:
      - poke-network

networks:
  poke-network: