
server:
  port: 8888

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pokewith?serverTimezone=Asia/Seoul
    username: root
    password: root1234
    hikari:
      maximum-pool-size: 20

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

  thymeleaf:
    suffix: .html
    cache: false

  mvc:
    static-path-pattern: "/static/**"