POST http://localhost:8888/api/signup
Content-Type: application/json

{
  "email" : "abc@abc.com",
  "password" : "qwe123qwe123!",
  "nickname1" : "pokepoke",
  "friendCode1" : "1234-1234-1234-1234"
}

###
POST http://localhost:8888/api/login
Content-Type: application/json

{
  "email" : "abc@abc.com",
  "password" : "qwe123qwe123!"
}

###
POST http://localhost:8888/api/email
Content-Type: application/json

{
  "email" : "abc@abc.com"
}

###
GET http://localhost:8888/api/user/test
